# Generated by Django 3.0.7 on 2020-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200704_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, height_field=5, null=True, upload_to='books-pics', verbose_name='Фото обложки', width_field=5),
        ),
    ]
