# Generated by Django 3.0.7 on 2020-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('genres', '0003_auto_20200703_0515'),
        ('books', '0010_auto_20200708_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='authors.Author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='genres.Genre', verbose_name='Жанр книги'),
        ),
    ]
