# Generated by Django 3.0.7 on 2020-07-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('genres', '0003_auto_20200703_0515'),
        ('books', '0012_auto_20200708_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Автор книги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genres.Genre', verbose_name='Жанр книги'),
        ),
    ]
