# Generated by Django 3.0.7 on 2020-07-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_auto_20200703_0515'),
        ('authors', '0001_initial'),
        ('books', '0014_auto_20200708_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.CharField(default='0+', max_length=10, verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='book',
            name='form',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default='0', verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='post_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='0', max_length=10, verbose_name='Стоимость книги BYN'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Автор книги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.Genre', verbose_name='Жанр книги'),
        ),
    ]
