# Generated by Django 3.0.7 on 2020-07-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
        ('books', '0016_auto_20200709_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publishing.Publishing', verbose_name='Издательство'),
            preserve_default=False,
        ),
    ]
