# Generated by Django 3.0.7 on 2020-07-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('publishing', '0001_initial'),
        ('genres', '0003_auto_20200703_0515'),
        ('books', '0019_auto_20200722_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(limit_choices_to={'book': True}, on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(limit_choices_to={'book': True}, on_delete=django.db.models.deletion.CASCADE, to='genres.Genre', verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(limit_choices_to={'book': True}, on_delete=django.db.models.deletion.CASCADE, to='publishing.Publishing', verbose_name='Издательство'),
        ),
    ]
