# Generated by Django 3.0.7 on 2020-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20200703_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название жанра'),
        ),
    ]
