# Generated by Django 3.0.7 on 2020-07-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200724_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(max_length=13, verbose_name='Контактный телефон'),
        ),
    ]
