# Generated by Django 3.0.7 on 2020-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('profiles', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(default='Customers', related_name='groups', to='auth.Group'),
        ),
    ]
