# Generated by Django 3.0.7 on 2020-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Ivan', max_length=20, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Ivanov', max_length=20, verbose_name='Имя'),
        ),
    ]
