# Generated by Django 3.0.7 on 2020-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200724_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='ул.Советская 7-22', max_length=20, verbose_name='Адрес'),
        ),
    ]
