# Generated by Django 3.0.7 on 2020-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200722_0152'),
        ('cart', '0002_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterUniqueTogether(
            name='bookincart',
            unique_together={('cart', 'book')},
        ),
    ]
